### ISSUE TITLE
iOS 9.0 build target

### ISSUE THREAD

**Issue by alexbuijs** [nordnet/cordova-universal-links-plugin#20]
Hi, thanks for your nice plugin! One question: why do you set the iOS build target to 9.0? The project compiles just fine through XCode without it, right? Setting the IPHONEOS_DEPLOYMENT_TARGET to 9.0 severely limits the use of apps which include this plugin. Why not just remove your script? That way apps on iOS 9 devices will be able to use universal links and older devices will be able to continue to work without it. Graceful degradation...

**Comment by nikDemyankov** [comment]
Yes, that could be done. Thanks for the idea)

**Comment by alexbuijs** [comment]
Awesome!

**Comment by nikDemyankov** [comment]
Downgraded to iOS 8. For that devices plugin just not gonna work, but will build and run. For newer devices - it will work as it should. Will release as soon as I'll finish with other issues in the milestone.

**Comment by alexbuijs** [comment]
Thanks, but why set a minimum required version at all? Some users may be stuck at iOS version 6 or 7.

**Comment by nikDemyankov** [comment]
Probably it will work, but I don't have a way to check that. So, basically, just don't want to risk that. 

By having iOS 8 as deployment target you cover over 92% of all devices. I think eventually Cordova will drop them off, as they do with Android. For it they have a rule of 5%: if platform is less then on 5% of devices - it is removed from supported. 

If a developer is sure, that his app will work on older devices - he can always create a fork and remove this part of the hook.

**Comment by alexbuijs** [comment]
Thanks, that's actually what I did, because I don't want to exclude potential users, even though there may not be many...

FYI: I think your plugin works just fine on iOS 6 & 7. It compiles fine with that target and submission to the app store went fine as well.

**Comment by nikDemyankov** [comment]
It compiles fine, since you are using latest SDK for building. And Apple approves it since they don't do UL testing. Plus, you should not rely on them: Apple review is a very weird and unreliable thing. They can easily submit app, that will crash on some devices. That's a developers and QA's job is to make sure, that it works fine on all devices, that you are aiming. So don't rely on Apple.

There is a small chance that plugin will crash on the runtime because of running on the older versions of iOS. It should not, but again: don't want to put out something that is not checked properly... Sorry.
