### ISSUE TITLE
How to allow user to open link in external browser from App

### ISSUE THREAD

**Issue by anilsaxena** [nordnet/cordova-universal-links-plugin#51]
I want user to give ability to open links which are opened by default in App to open in browser. By when I call windows.open(link_url, "_system") it goes in loop on Android, it works on IOS though.

**Comment by nikDemyankov** [comment]
Not sure, that this can be done. The problem is that by default Android will open all your UL links in the app, not a browser. Because it's a default behaviour for him and controlled by OS, not by plugin. 

You can do a kind of the hack by defining one url in `config.xml` , but from the JS side opening some other, which leads to the same page. For example: 
1. Define in `config.xml`:
   
   ``` xml
   <universal-links>
     <host name="example.com" scheme="https">
       <path url="/path/*.html" event="ul_event" />
     </host>
   </universal-links>
   ```
2. Launch app by clicking on `https://example.com/path/index.html`
3. To launch same page in browser - call from JS:
   
   ``` js
   window.open('https://example.com/path/index.html#external', '_system');
   ```

**Comment by anilsaxena** [comment]
Thanks for the interesting idea, I will try it.

**Comment by nikDemyankov** [comment]
It's kind of dirty, but hope it will work :)

**Comment by anilsaxena** [comment]
I realized most of  my url are like /pages/page_id so not able to use pattern like *.index.html

**Comment by nikDemyankov** [comment]
Then I'm afraid this can't be done. As I said before - this is controlled by Android. 

The other workaround can be writing native plugin, that accepts the link to open, and it will launch selector, with which app to open this link, so the user could choose the browser.

Or force-open in the browser; but for that you would need explicitly launch browser app.

**Comment by alaa-alshamy** [comment]
@anilsaxena @nikDemyankov  any updates here ? is it still can't be done in android ?
