### ISSUE TITLE
Unable to integrate

### ISSUE THREAD

**Issue by kael-moreno** [nordnet/cordova-universal-links-plugin#62]
Hi,

I'm trying to use this plugin, but it doesn't work. I did all the steps in the integration, but it doesn't launch the app and only redirects to the page of our site. Anyone can help me or assist me for this?

Thanks!

**Comment by nikDemyankov** [comment]
Hi,

Can you share some more info like: what platform, what is your setup in `config.xml`, how you've been testing it?

**Comment by kael-moreno** [comment]
Hi,

I'm using iOS platform. In config, I added this:

``` xml
<universal-links>
     <host name="travelbook.ph" />
</universal-links>
```

I tested it by making a simple site that has a link of our site as: 

``` html
<a href="http://travelbook.ph">Link Here</a> 
```

I'm building through Intel XDK. Do I need to build it for production or build it through cordova CLI?

Thanks,

Kael

**Comment by nikDemyankov** [comment]
Fixed markdown in your last post, otherwise could not see xml and html code.

Plugin is using JS hooks to configure the native project to support universal links. Don't know if Intel XDK is executing them... To check this you can open native iOS project in Xcode and open `Capabilities` tab. If `Associated Domains` is `on` and in `domains` list you see `travelbook.ph` - then it's fine. If not - then you need either build your project from CLI by running `cordova build`; or configure it manually as I pointed in https://github.com/nordnet/cordova-universal-links-plugin/issues/60 .

Also, not sure that you can run universal links other http. I think it is required to have https.

Another thing: don't test on emulator, use real device. And first try to launch the app from the link in the email instead of the browser.

**Comment by kael-moreno** [comment]
Thanks! However, I tested it in email, and its not opening the app, but the browser. I'm using iOS 9.2.1.

**Comment by nikDemyankov** [comment]
What about other things I mentioned? Have you checked the resulting project in Xcode?

Also, since you are using http - make sure, that you signed your `apple-app-site-association` file with the valid SSL certificate. And that it is placed in the root of your domain and available without any redirects.

**Comment by KeithTurkowski** [comment]
Were you ever able to get this working in the Intel XDK?
