### ISSUE TITLE
Not working in ios or android

### ISSUE THREAD

**Issue by krisbrkrunch** [nordnet/cordova-universal-links-plugin#69]
Have followed all the directions verified our apple-app-site-association defnitely have the correct applinks:url enabled in the xcode project but doesnt work no matter what I do. I have tried creating a native ios app with the same bundle id and entitlements and the universal links work perfectly fine. so its not a server issue not an apple issue certificate or provisioning profile, Its only in our cordova project that the links do not open the app. links are being clicked from imessage.

Weve tried on android as well and the links do not open there either. Seems like something is not right somewhere.

**Comment by nikDemyankov** [comment]
Have you tried to compare configurations in cordova project and native project? Also, are you testing plugin on your current app or on some empty project?

We can start investigation from Android since it's easier to set it up. Just create a new Cordova Android project, add this plugin to it. Then do the configuration in the `config.xml` similar to the one you already have. And then check if it's opened by running: 

```
adb shell am start
        -W -a android.intent.action.VIEW
        -d <URI> <PACKAGE>
```

Everything is described [here](https://github.com/nordnet/cordova-universal-links-plugin#testing-ul-for-android-locally).

**Comment by krisbrkrunch** [comment]
Couldnt get android running on my mac but I did make some progress creating a test cordova ios app with the same settings as before in my native ios test the cordova test app launched and worked. I reopened my main cordova project that has the problem and verified all the settings are the same! I cannot figure out why its not working in our app, something must be overriding the universal links somewhere It just doesnt make any sense. I don't know what else to troubleshoot, any more ideas?

**Comment by nikDemyankov** [comment]
Can you give the list of plugins in your main ios project?

**Comment by krisbrkrunch** [comment]
android.json
cordova-plugin-app-event
cordova-plugin-camera
cordova-plugin-compat
cordova-plugin-device
cordova-plugin-facebook4
cordova-plugin-splashscreen
cordova-plugin-whitelist
cordova-plugin-x-socialsharing
cordova-universal-links-plugin
de.appplant.cordova.plugin.local-notification
fetch.json
ios.json

**Comment by nikDemyankov** [comment]
Can't find anything, that blocks UL plugin...
Have you tried to add them one by one to the working Cordova iOS project to understand, which one is breaking the UL support?
