### ISSUE TITLE
load apple-app-site-association

### ISSUE THREAD

**Issue by scutzxb** [nordnet/cordova-universal-links-plugin#84]
As i can see the from the http requests by Fiddler debugger, my app didn't send any request to load the apple-app-site-association file. Anything wrong?

My config.xml is below:

`<widget id="com.myapp" version="1.0" versionCode="1">`
  
  `<univeral-links>`
    `<ios-team-id vlalue="9G4RX4C32N" />`
    `<host name="myappsite.com" scheme="https">` 
      `<path url="*"/>`
      `<path url="/"/>`
   `</host>`
  `</univeral-links>`
`</widget>`

**Comment by nikDemyankov** [comment]
I think it's a Safari who loads it, not the app. App is just registered to handle the links of certain type. 

Also, I think you have a typo in `<ios-team-id vlalue="9G4RX4C32N" />`. Should be `value`, not `vlalue`. Don't know if it's in your actual config.xml or not, though.

Instead of 

``` xml
<host name="myappsite.com" scheme="https"> 
  <path url="*"/>
  <path url="/"/>
</host>
```

Try to use:

``` xml
<host name="myappsite.com" scheme="https" /> 
```

Anyway, troubleshooting for UL is:
- make sure you configured your app properly in the developer console, as described in the [docs](https://github.com/nordnet/cordova-universal-links-plugin#ios-web-integration).
- make sure, that `https://myappsite.com/apple-app-site-association` is accessible and file can be downloaded, no redirects are allowed.

After that - send a link like `https://myappsite.com/some/path` on email and click on it from your phone. It should open in the app.
