### ISSUE TITLE
Android Deep Link Not firing on Resume

### ISSUE THREAD

**Issue by mikeduarte** [nordnet/cordova-universal-links-plugin#9]
@nikDemyankov 

I'm having an issue on Android.  If my app is not running and I click on a link that launches the app, the app loads from a cold start and the universal link plugin event fires just fine.  If I leave the app running, then click on another link, the app opens, fires the onResume event, but the universal plugin link event doesn't seem to fire.  Any ideas?

My device is running Android 4.4.2 and tested on another device running 4.4.4.  Both have same issue.

**Comment by nikDemyankov** [comment]
Not yet, but I will look into that, thanks.

**Comment by nikDemyankov** [comment]
Yep, this is a bug. If you press "Home" button - app is still alive in the background. And if you launch it again from the link - event is not firing. But if you press "Back" button and then launch from link - it works. Will try to fix it soon.

**Comment by nikDemyankov** [comment]
Okey, this should work now. If application was launched from the link "A", putted to sleep by pressing "Home" button, and then resumed by clicking on link "B" - JS event is firing. 

But if you launched app from the link "A", putted app to sleep, and then resumed by clicking on the same "A" link - event is not gonna fire, because this is an old Intent, and android (or cordova) not gonna tell us about it. But, probably, that's fine, since we already handled that intent and no need to do it again.
